GET http://localhost:8000/todo/

###

POST http://localhost:8000/todo/
content-type: application/json

{
    "name": "name is nothing",
    "detail": "test"
}

###

GET http://localhost:8000/todo/20/

###

PUT http://localhost:8000/todo/111/
content-type: application/json

{
    "name": "test",
    "detail": "fasd"
}

###

DELETE http://localhost:8000/todo/31/
