# Generated by Django 3.2 on 2022-06-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='detail',
            field=models.CharField(db_column='description', max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(db_column='title', max_length=20, verbose_name='name'),
        ),
    ]
